name: Auto Check-in
on:
  schedule:
    - cron: '* * * * *'
jobs:
  check-in:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run check-in script
        run: |
            python auto_checkin.py

